//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Admin.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string LblAdminTitle_Text {
            get {
                return ResourceManager.GetString("LblAdminTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string LblHomeLink_Text {
            get {
                return ResourceManager.GetString("LblHomeLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string LnkSelectAccounts_Text {
            get {
                return ResourceManager.GetString("LnkSelectAccounts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Home.
        /// </summary>
        public static string LnkSelectAdminHome_Text {
            get {
                return ResourceManager.GetString("LnkSelectAdminHome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string LnkSelectCategories_Text {
            get {
                return ResourceManager.GetString("LnkSelectCategories_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string LnkSelectConfig_Text {
            get {
                return ResourceManager.GetString("LnkSelectConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Editing.
        /// </summary>
        public static string LnkSelectContent_Text {
            get {
                return ResourceManager.GetString("LnkSelectContent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Admin Home.
        /// </summary>
        public static string LnkSelectGlobalAdminHome_Text {
            get {
                return ResourceManager.GetString("LnkSelectGlobalAdminHome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Configuration.
        /// </summary>
        public static string LnkSelectGlobalConfig_Text {
            get {
                return ResourceManager.GetString("LnkSelectGlobalConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string LnkSelectGroups_Text {
            get {
                return ResourceManager.GetString("LnkSelectGroups_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Export.
        /// </summary>
        public static string LnkSelectImportExport_Text {
            get {
                return ResourceManager.GetString("LnkSelectImportExport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Log.
        /// </summary>
        public static string LnkSelectLog_Text {
            get {
                return ResourceManager.GetString("LnkSelectLog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        public static string LnkSelectNamespaces_Text {
            get {
                return ResourceManager.GetString("LnkSelectNamespaces_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav. Paths.
        /// </summary>
        public static string LnkSelectNavPaths_Text {
            get {
                return ResourceManager.GetString("LnkSelectNavPaths_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki Pages.
        /// </summary>
        public static string LnkSelectPages_Text {
            get {
                return ResourceManager.GetString("LnkSelectPages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Configuration.
        /// </summary>
        public static string LnkSelectPluginsConfiguration_Text {
            get {
                return ResourceManager.GetString("LnkSelectPluginsConfiguration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Management.
        /// </summary>
        public static string LnkSelectPluginsManagement_Text {
            get {
                return ResourceManager.GetString("LnkSelectPluginsManagement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets/Templates.
        /// </summary>
        public static string LnkSelectSnippets_Text {
            get {
                return ResourceManager.GetString("LnkSelectSnippets_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string LnkSelectTheme_Text {
            get {
                return ResourceManager.GetString("LnkSelectTheme_Text", resourceCulture);
            }
        }
    }
}
