//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Admin.AdminHome", typeof(AdminHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string BtnRebuild_Text {
            get {
                return ResourceManager.GetString("BtnRebuild_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild this index.
        /// </summary>
        public static string BtnRebuild_ToolTip {
            get {
                return ResourceManager.GetString("BtnRebuild_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string BtnRebuild2_Text {
            get {
                return ResourceManager.GetString("BtnRebuild2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild this index.
        /// </summary>
        public static string BtnRebuild2_ToolTip {
            get {
                return ResourceManager.GetString("BtnRebuild2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild Page Links.
        /// </summary>
        public static string BtnRebuildPageLinks_Text {
            get {
                return ResourceManager.GetString("BtnRebuildPageLinks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild the links structure.
        /// </summary>
        public static string BtnRebuildPageLinks_ToolTip {
            get {
                return ResourceManager.GetString("BtnRebuildPageLinks_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Bulk Email.
        /// </summary>
        public static string BtnSendBulkEmail_Text {
            get {
                return ResourceManager.GetString("BtnSendBulkEmail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BtnSendBulkEmail_ToolTip {
            get {
                return ResourceManager.GetString("BtnSendBulkEmail_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one group.
        /// </summary>
        public static string CvGroups_ErrorMessage {
            get {
                return ResourceManager.GetString("CvGroups_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string LblAdminHome_Text {
            get {
                return ResourceManager.GetString("LblAdminHome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Email.
        /// </summary>
        public static string LblBulkEmail_Text {
            get {
                return ResourceManager.GetString("LblBulkEmail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send an email message to all users of one or more groups..
        /// </summary>
        public static string LblBulkEmailInfo_Text {
            get {
                return ResourceManager.GetString("LblBulkEmailInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Index Status.
        /// </summary>
        public static string LblIndexStatus_Text {
            get {
                return ResourceManager.GetString("LblIndexStatus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked in.
        /// </summary>
        public static string LblLinkedIn_Text {
            get {
                return ResourceManager.GetString("LblLinkedIn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Pages.
        /// </summary>
        public static string LblMissingPages_Text {
            get {
                return ResourceManager.GetString("LblMissingPages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string LblNamespace_Text {
            get {
                return ResourceManager.GetString("LblNamespace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphan Pages.
        /// </summary>
        public static string LblOrphanPages_Text {
            get {
                return ResourceManager.GetString("LblOrphanPages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Note&lt;/b&gt;: a page is considered an &lt;i&gt;orphan&lt;/i&gt; when it has no incoming links from other pages..
        /// </summary>
        public static string LblOrphanPagesInfo_Text {
            get {
                return ResourceManager.GetString("LblOrphanPagesInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orphan pages in the wiki.
        /// </summary>
        public static string LblOrphanPagesInfoPost_Text {
            get {
                return ResourceManager.GetString("LblOrphanPagesInfoPost_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seem to be .
        /// </summary>
        public static string LblOrphanPagesInfoPre_Text {
            get {
                return ResourceManager.GetString("LblOrphanPagesInfoPre_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name.
        /// </summary>
        public static string LblPage_Text {
            get {
                return ResourceManager.GetString("LblPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string LblProvider_Text {
            get {
                return ResourceManager.GetString("LblProvider_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Warning&lt;/b&gt;: rebuilding a search index might take some time. Please do not close this screen while the index is being rebuilt. If you experience timeouts, increase the request execution timeout in the web.config..
        /// </summary>
        public static string LblRebuildIndexInfo_Text {
            get {
                return ResourceManager.GetString("LblRebuildIndexInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Warning&lt;/b&gt;: rebuilding page links might take some time. Please do not close this screen while the links are being rebuilt. If you experience timeouts, increase the request execution timeout in the web.config..
        /// </summary>
        public static string LblRebuildPageLinksInfo_Text {
            get {
                return ResourceManager.GetString("LblRebuildPageLinksInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string LblSubject_Text {
            get {
                return ResourceManager.GetString("LblSubject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see Pages.
        /// </summary>
        public static string LnkPages_Text {
            get {
                return ResourceManager.GetString("LnkPages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Pages administration tab.
        /// </summary>
        public static string LnkPages_ToolTip {
            get {
                return ResourceManager.GetString("LnkPages_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Page2_Title {
            get {
                return ResourceManager.GetString("Page2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body is required.
        /// </summary>
        public static string RfvBody_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvBody_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required.
        /// </summary>
        public static string RfvSubject_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvSubject_ErrorMessage", resourceCulture);
            }
        }
    }
}
