//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminGroups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminGroups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Admin.AdminGroups", typeof(AdminGroups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel_Text {
            get {
                return ResourceManager.GetString("BtnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and return to the Group list.
        /// </summary>
        public static string BtnCancel_ToolTip {
            get {
                return ResourceManager.GetString("BtnCancel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string BtnCreate_Text {
            get {
                return ResourceManager.GetString("BtnCreate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the new Group.
        /// </summary>
        public static string BtnCreate_ToolTip {
            get {
                return ResourceManager.GetString("BtnCreate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BtnDelete_Text {
            get {
                return ResourceManager.GetString("BtnDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the Group.
        /// </summary>
        public static string BtnDelete_ToolTip {
            get {
                return ResourceManager.GetString("BtnDelete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        public static string BtnNewGroup_Text {
            get {
                return ResourceManager.GetString("BtnNewGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new User Group.
        /// </summary>
        public static string BtnNewGroup_ToolTip {
            get {
                return ResourceManager.GetString("BtnNewGroup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Group.
        /// </summary>
        public static string BtnSave_Text {
            get {
                return ResourceManager.GetString("BtnSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save modifications.
        /// </summary>
        public static string BtnSave_ToolTip {
            get {
                return ResourceManager.GetString("BtnSave_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string BtnSelect_Text {
            get {
                return ResourceManager.GetString("BtnSelect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this User Group.
        /// </summary>
        public static string BtnSelect_ToolTip {
            get {
                return ResourceManager.GetString("BtnSelect_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already in use.
        /// </summary>
        public static string CvName_ErrorMessage {
            get {
                return ResourceManager.GetString("CvName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CvName_Text {
            get {
                return ResourceManager.GetString("CvName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LblDescription_Text {
            get {
                return ResourceManager.GetString("LblDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Details.
        /// </summary>
        public static string LblEditTitle_Text {
            get {
                return ResourceManager.GetString("LblEditTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Permissions.
        /// </summary>
        public static string LblGlobalPermissions_Text {
            get {
                return ResourceManager.GetString("LblGlobalPermissions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string LblGroups_Text {
            get {
                return ResourceManager.GetString("LblGroups_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LblName_Text {
            get {
                return ResourceManager.GetString("LblName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string LblProvider_Text {
            get {
                return ResourceManager.GetString("LblProvider_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblResult_Text {
            get {
                return ResourceManager.GetString("LblResult_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string LblUsers_Text {
            get {
                return ResourceManager.GetString("LblUsers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string RevName_ErrorMessage {
            get {
                return ResourceManager.GetString("RevName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RevName_Text {
            get {
                return ResourceManager.GetString("RevName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string RfvName_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RfvName_Text {
            get {
                return ResourceManager.GetString("RfvName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TxtDescription_Text {
            get {
                return ResourceManager.GetString("TxtDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TxtName_Text {
            get {
                return ResourceManager.GetString("TxtName_Text", resourceCulture);
            }
        }
    }
}
