//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Install {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstallStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Install.InstallStrings", typeof(InstallStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string ButtonTest {
            get {
                return ResourceManager.GetString("ButtonTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred installing.
        /// </summary>
        public static string FailureInstall {
            get {
                return ResourceManager.GetString("FailureInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string SharedBack {
            get {
                return ResourceManager.GetString("SharedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SharedCancel {
            get {
                return ResourceManager.GetString("SharedCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of.
        /// </summary>
        public static string SharedCheckLengthError1 {
            get {
                return ResourceManager.GetString("SharedCheckLengthError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be between.
        /// </summary>
        public static string SharedCheckLengthError2 {
            get {
                return ResourceManager.GetString("SharedCheckLengthError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string SharedCheckLengthError3 {
            get {
                return ResourceManager.GetString("SharedCheckLengthError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string SharedContinue {
            get {
                return ResourceManager.GetString("SharedContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SharedDelete {
            get {
                return ResourceManager.GetString("SharedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure!.
        /// </summary>
        public static string SharedFailure {
            get {
                return ResourceManager.GetString("SharedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SharedNextButton {
            get {
                return ResourceManager.GetString("SharedNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string SharedSuccess {
            get {
                return ResourceManager.GetString("SharedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SharedUnexpectedError {
            get {
                return ResourceManager.GetString("SharedUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Stage1 {
            get {
                return ResourceManager.GetString("Stage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Stage2 {
            get {
                return ResourceManager.GetString("Stage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Stage3 {
            get {
                return ResourceManager.GetString("Stage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Stage4 {
            get {
                return ResourceManager.GetString("Stage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank for you downloading ScrewTurnWiki engine..
        /// </summary>
        public static string Step1Intro {
            get {
                return ResourceManager.GetString("Step1Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step1PublicDirectory {
            get {
                return ResourceManager.GetString("Step1PublicDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to the public directory..
        /// </summary>
        public static string Step1PublicDirectoryFailureMessage {
            get {
                return ResourceManager.GetString("Step1PublicDirectoryFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step1PublicDirectoryHelp {
            get {
                return ResourceManager.GetString("Step1PublicDirectoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public directory can be written to..
        /// </summary>
        public static string Step1PublicDirectorySuccessMessage {
            get {
                return ResourceManager.GetString("Step1PublicDirectorySuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step1WebConfig {
            get {
                return ResourceManager.GetString("Step1WebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to the web.config file..
        /// </summary>
        public static string Step1WebConfigFailureMessage {
            get {
                return ResourceManager.GetString("Step1WebConfigFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to proceed, first we need to test if you have write access to the web.config file..
        /// </summary>
        public static string Step1WebConfigHelp {
            get {
                return ResourceManager.GetString("Step1WebConfigHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: you will need to create the database first..
        /// </summary>
        public static string Step2ConnectionStringCreateDatabase {
            get {
                return ResourceManager.GetString("Step2ConnectionStringCreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string Step2ConnectionStrings {
            get {
                return ResourceManager.GetString("Step2ConnectionStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step2ConnectionStringsHelp {
            get {
                return ResourceManager.GetString("Step2ConnectionStringsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        public static string Step2DatabaseConnectionString {
            get {
                return ResourceManager.GetString("Step2DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database type.
        /// </summary>
        public static string Step2DatabaseType {
            get {
                return ResourceManager.GetString("Step2DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example connection strings.
        /// </summary>
        public static string Step2ExampleConnectionStrings {
            get {
                return ResourceManager.GetString("Step2ExampleConnectionStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step2Intro {
            get {
                return ResourceManager.GetString("Step2Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step2TestDbConnectionFailureMessage {
            get {
                return ResourceManager.GetString("Step2TestDbConnectionFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new wiki.
        /// </summary>
        public static string Step3ButtonCreateNewWikiTitle {
            get {
                return ResourceManager.GetString("Step3ButtonCreateNewWikiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a wiki.
        /// </summary>
        public static string Step3ButtonCreateWikiTitle {
            get {
                return ResourceManager.GetString("Step3ButtonCreateWikiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All form fields are required..
        /// </summary>
        public static string Step3FieldsRequireMessage {
            get {
                return ResourceManager.GetString("Step3FieldsRequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts field only allow : any letter, 0-9, underscores, dash, semicolon, point.
        /// </summary>
        public static string Step3HostsInValidCharacters {
            get {
                return ResourceManager.GetString("Step3HostsInValidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step3HostsTitleColumnHeading {
            get {
                return ResourceManager.GetString("Step3HostsTitleColumnHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step3Intro {
            get {
                return ResourceManager.GetString("Step3Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wikiname is exists.
        /// </summary>
        public static string Step3WikinameExistsError {
            get {
                return ResourceManager.GetString("Step3WikinameExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikiname field only allow : any letter, 0-9, underscores, dash.
        /// </summary>
        public static string Step3WikinameInValidCharacters {
            get {
                return ResourceManager.GetString("Step3WikinameInValidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step3WikiNameTitleColumnHeading {
            get {
                return ResourceManager.GetString("Step3WikiNameTitleColumnHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Password.
        /// </summary>
        public static string Step4BtnPasswordSave_Text {
            get {
                return ResourceManager.GetString("Step4BtnPasswordSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Master Password.
        /// </summary>
        public static string Step4ChangeMasterPassword_Text {
            get {
                return ResourceManager.GetString("Step4ChangeMasterPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal.
        /// </summary>
        public static string Step4CheckEqualPasswordMessage {
            get {
                return ResourceManager.GetString("Step4CheckEqualPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must configure the password for the built-in &apos;admin&apos; account. Make sure you use a very strong password as the built-in &apos;admin&apos; account can perform any operation in the wiki..
        /// </summary>
        public static string Step4DescriptionPassword_Text {
            get {
                return ResourceManager.GetString("Step4DescriptionPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go back through the installation steps and check your settings. The error message was:.
        /// </summary>
        public static string Step4FailureGoBackAndCheck {
            get {
                return ResourceManager.GetString("Step4FailureGoBackAndCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the install.
        /// </summary>
        public static string Step4FailureTitle {
            get {
                return ResourceManager.GetString("Step4FailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart site.
        /// </summary>
        public static string Step4FinalizeInstall {
            get {
                return ResourceManager.GetString("Step4FinalizeInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password saved successfully.
        /// </summary>
        public static string Step4NewAdminPassResultMessage {
            get {
                return ResourceManager.GetString("Step4NewAdminPassResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Step4NewPassword {
            get {
                return ResourceManager.GetString("Step4NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step4NewPassword_Text {
            get {
                return ResourceManager.GetString("Step4NewPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here the master password.
        /// </summary>
        public static string Step4NewPassword_ToolTip {
            get {
                return ResourceManager.GetString("Step4NewPassword_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field only allow : a-z 0-9.
        /// </summary>
        public static string Step4PasswordInvalidCharactersMessage {
            get {
                return ResourceManager.GetString("Step4PasswordInvalidCharactersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required. Length of password must be between 6 and 30..
        /// </summary>
        public static string Step4PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("Step4PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password (Repeat).
        /// </summary>
        public static string Step4ReNewPassword {
            get {
                return ResourceManager.GetString("Step4ReNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step4ReNewPassword_Text {
            get {
                return ResourceManager.GetString("Step4ReNewPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the master password.
        /// </summary>
        public static string Step4ReNewPassword_ToolTip {
            get {
                return ResourceManager.GetString("Step4ReNewPassword_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Step4SuccessSummary {
            get {
                return ResourceManager.GetString("Step4SuccessSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation successful.
        /// </summary>
        public static string Step4SuccessTitle {
            get {
                return ResourceManager.GetString("Step4SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of public directory is empty..
        /// </summary>
        public static string ValidationPublicDirectoryEmpty {
            get {
                return ResourceManager.GetString("ValidationPublicDirectoryEmpty", resourceCulture);
            }
        }
    }
}
