//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Edit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Edit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Common.Edit", typeof(Edit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BtnAutoTemplateOK_Text {
            get {
                return ResourceManager.GetString("BtnAutoTemplateOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this message.
        /// </summary>
        public static string BtnAutoTemplateOK_ToolTip {
            get {
                return ResourceManager.GetString("BtnAutoTemplateOK_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel_Text {
            get {
                return ResourceManager.GetString("BtnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BtnCancel_ToolTip {
            get {
                return ResourceManager.GetString("BtnCancel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancelTemplate_Text {
            get {
                return ResourceManager.GetString("BtnCancelTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the Templates toolbar.
        /// </summary>
        public static string BtnCancelTemplate_ToolTip {
            get {
                return ResourceManager.GetString("BtnCancelTemplate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string BtnCreateCategory_Text {
            get {
                return ResourceManager.GetString("BtnCreateCategory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BtnCreateCategory_ToolTip {
            get {
                return ResourceManager.GetString("BtnCreateCategory_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify page name manually....
        /// </summary>
        public static string BtnManualName_Text {
            get {
                return ResourceManager.GetString("BtnManualName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BtnManualName_ToolTip {
            get {
                return ResourceManager.GetString("BtnManualName_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave_Text {
            get {
                return ResourceManager.GetString("BtnSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BtnSave_ToolTip {
            get {
                return ResourceManager.GetString("BtnSave_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string BtnSaveAndContinue_Text {
            get {
                return ResourceManager.GetString("BtnSaveAndContinue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BtnSaveAndContinue_ToolTip {
            get {
                return ResourceManager.GetString("BtnSaveAndContinue_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Templates....
        /// </summary>
        public static string BtnTemplates_Text {
            get {
                return ResourceManager.GetString("BtnTemplates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BtnTemplates_ToolTip {
            get {
                return ResourceManager.GetString("BtnTemplates_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Template.
        /// </summary>
        public static string BtnUseTemplate_Text {
            get {
                return ResourceManager.GetString("BtnUseTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this Template (replace current content).
        /// </summary>
        public static string BtnUseTemplate_ToolTip {
            get {
                return ResourceManager.GetString("BtnUseTemplate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Change (no backup).
        /// </summary>
        public static string ChkMinorChange_Text {
            get {
                return ResourceManager.GetString("ChkMinorChange_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChkMinorChange_ToolTip {
            get {
                return ResourceManager.GetString("ChkMinorChange_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Draft.
        /// </summary>
        public static string ChkSaveAsDraft_Text {
            get {
                return ResourceManager.GetString("ChkSaveAsDraft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChkSaveAsDraft_ToolTip {
            get {
                return ResourceManager.GetString("ChkSaveAsDraft_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string CvCategory1_ErrorMessage {
            get {
                return ResourceManager.GetString("CvCategory1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CvCategory1_Text {
            get {
                return ResourceManager.GetString("CvCategory1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CvCategory1_ToolTip {
            get {
                return ResourceManager.GetString("CvCategory1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category already exists.
        /// </summary>
        public static string CvCategory2_ErrorMessage {
            get {
                return ResourceManager.GetString("CvCategory2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CvCategory2_Text {
            get {
                return ResourceManager.GetString("CvCategory2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CvCategory2_ToolTip {
            get {
                return ResourceManager.GetString("CvCategory2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Page Name.
        /// </summary>
        public static string CvName1_ErrorMessage {
            get {
                return ResourceManager.GetString("CvName1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CvName1_Text {
            get {
                return ResourceManager.GetString("CvName1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CvName1_ToolTip {
            get {
                return ResourceManager.GetString("CvName1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page already exists.
        /// </summary>
        public static string CvName2_ErrorMessage {
            get {
                return ResourceManager.GetString("CvName2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CvName2_Text {
            get {
                return ResourceManager.GetString("CvName2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CvName2_ToolTip {
            get {
                return ResourceManager.GetString("CvName2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes to this page will be saved in a draft and they will not be published until an editor or administrator approves them..
        /// </summary>
        public static string LblApprovalRequiredInfo_Text {
            get {
                return ResourceManager.GetString("LblApprovalRequiredInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Attachments Management.
        /// </summary>
        public static string LblAttachmentManager_Text {
            get {
                return ResourceManager.GetString("LblAttachmentManager_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Content Template &quot;##TEMPLATE##&quot; was selected automatically. You can discard the content as well as select another Template using the link above..
        /// </summary>
        public static string LblAutoTemplate_Text {
            get {
                return ResourceManager.GetString("LblAutoTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Categories.
        /// </summary>
        public static string LblCategories_Text {
            get {
                return ResourceManager.GetString("LblCategories_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblCategoryResult_Text {
            get {
                return ResourceManager.GetString("LblCategoryResult_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblCategoryResult_ToolTip {
            get {
                return ResourceManager.GetString("LblCategoryResult_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment for this change.
        /// </summary>
        public static string LblComment_Text {
            get {
                return ResourceManager.GetString("LblComment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Warning&lt;/b&gt;: this Page is being edited by another user.
        /// </summary>
        public static string LblConcurrentEditing_Text {
            get {
                return ResourceManager.GetString("LblConcurrentEditing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblConcurrentEditingUsername_Text {
            get {
                return ResourceManager.GetString("LblConcurrentEditingUsername_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description.
        /// </summary>
        public static string LblDescription_Text {
            get {
                return ResourceManager.GetString("LblDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently editing a previously saved &lt;b&gt;draft&lt;/b&gt; of this page, edited by &lt;b&gt;##USER##&lt;/b&gt; on &lt;b&gt;##DATETIME##&lt;/b&gt; (##VIEWCHANGES##)..
        /// </summary>
        public static string LblDraftInfo_Text {
            get {
                return ResourceManager.GetString("LblDraftInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you think this content is ready for display, simply uncheck the &apos;Save as Draft&apos; checkbox near the &apos;Save&apos; button. Note: drafts are not versioned..
        /// </summary>
        public static string LblDraftInfo2_Text {
            get {
                return ResourceManager.GetString("LblDraftInfo2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you are not logged in, your IP Address will be used as Username..
        /// </summary>
        public static string LblIpLogged_Text {
            get {
                return ResourceManager.GetString("LblIpLogged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keywords (separate with commas).
        /// </summary>
        public static string LblKeywords_Text {
            get {
                return ResourceManager.GetString("LblKeywords_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Information.
        /// </summary>
        public static string LblMeta_Text {
            get {
                return ResourceManager.GetString("LblMeta_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name (used for linking pages).
        /// </summary>
        public static string LblName_Text {
            get {
                return ResourceManager.GetString("LblName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string LblNewCategory_Text {
            get {
                return ResourceManager.GetString("LblNewCategory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblRefreshLink_Text {
            get {
                return ResourceManager.GetString("LblRefreshLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblResult_Text {
            get {
                return ResourceManager.GetString("LblResult_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblResult_ToolTip {
            get {
                return ResourceManager.GetString("LblResult_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving this Page might result in a &lt;b&gt;data-loss&lt;/b&gt;..
        /// </summary>
        public static string LblSaveDangerous_Text {
            get {
                return ResourceManager.GetString("LblSaveDangerous_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Administrators don&apos;t allow to save this Page..
        /// </summary>
        public static string LblSaveDisabled_Text {
            get {
                return ResourceManager.GetString("LblSaveDisabled_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblSessionRefresh_Text {
            get {
                return ResourceManager.GetString("LblSessionRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblTemplatePreview_Text {
            get {
                return ResourceManager.GetString("LblTemplatePreview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblTemplatePreview_ToolTip {
            get {
                return ResourceManager.GetString("LblTemplatePreview_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string LblTitle_Text {
            get {
                return ResourceManager.GetString("LblTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LblUnloadPage_Text {
            get {
                return ResourceManager.GetString("LblUnloadPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LstCategories_ToolTip {
            get {
                return ResourceManager.GetString("LstCategories_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LstTemplates_ToolTip {
            get {
                return ResourceManager.GetString("LstTemplates_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Page2_Title {
            get {
                return ResourceManager.GetString("Page2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlAnonymous_GroupingText {
            get {
                return ResourceManager.GetString("PnlAnonymous_GroupingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlAnonymous_ToolTip {
            get {
                return ResourceManager.GetString("PnlAnonymous_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlApprovalRequired_GroupingText {
            get {
                return ResourceManager.GetString("PnlApprovalRequired_GroupingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlApprovalRequired_ToolTip {
            get {
                return ResourceManager.GetString("PnlApprovalRequired_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlCaptcha_GroupingText {
            get {
                return ResourceManager.GetString("PnlCaptcha_GroupingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlCaptcha_ToolTip {
            get {
                return ResourceManager.GetString("PnlCaptcha_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlCategoryCreation_GroupingText {
            get {
                return ResourceManager.GetString("PnlCategoryCreation_GroupingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlCategoryCreation_ToolTip {
            get {
                return ResourceManager.GetString("PnlCategoryCreation_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlCollisions_GroupingText {
            get {
                return ResourceManager.GetString("PnlCollisions_GroupingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlCollisions_ToolTip {
            get {
                return ResourceManager.GetString("PnlCollisions_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlDraft_GroupingText {
            get {
                return ResourceManager.GetString("PnlDraft_GroupingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlDraft_ToolTip {
            get {
                return ResourceManager.GetString("PnlDraft_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlTemplates_GroupingText {
            get {
                return ResourceManager.GetString("PnlTemplates_GroupingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PnlTemplates_ToolTip {
            get {
                return ResourceManager.GetString("PnlTemplates_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string RfvCategory_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvCategory_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string RfvName_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string RfvTitle_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvTitle_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TxtCategory2_Text {
            get {
                return ResourceManager.GetString("TxtCategory2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of the category here.
        /// </summary>
        public static string TxtCategory2_ToolTip {
            get {
                return ResourceManager.GetString("TxtCategory2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a comment for this change here (optional).
        /// </summary>
        public static string TxtComment2_ToolTip {
            get {
                return ResourceManager.GetString("TxtComment2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the description for this page here (optional).
        /// </summary>
        public static string TxtDescription2_ToolTip {
            get {
                return ResourceManager.GetString("TxtDescription2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the keywords for this page here, separated with commas (optional).
        /// </summary>
        public static string TxtKeywords2_ToolTip {
            get {
                return ResourceManager.GetString("TxtKeywords2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TxtName2_Text {
            get {
                return ResourceManager.GetString("TxtName2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of the page here.
        /// </summary>
        public static string TxtName2_ToolTip {
            get {
                return ResourceManager.GetString("TxtName2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TxtTitle2_Text {
            get {
                return ResourceManager.GetString("TxtTitle2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the title of the page here.
        /// </summary>
        public static string TxtTitle2_ToolTip {
            get {
                return ResourceManager.GetString("TxtTitle2_ToolTip", resourceCulture);
            }
        }
    }
}
