//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Common.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BtnLogin_Text {
            get {
                return ResourceManager.GetString("BtnLogin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Login.
        /// </summary>
        public static string BtnLogin_ToolTip {
            get {
                return ResourceManager.GetString("BtnLogin_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string BtnLogout_Text {
            get {
                return ResourceManager.GetString("BtnLogout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Logout.
        /// </summary>
        public static string BtnLogout_ToolTip {
            get {
                return ResourceManager.GetString("BtnLogout_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string BtnResetPassword_Text {
            get {
                return ResourceManager.GetString("BtnResetPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save New Password.
        /// </summary>
        public static string BtnSaveNewPassword_Text {
            get {
                return ResourceManager.GetString("BtnSaveNewPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string ChkRemember_Text {
            get {
                return ResourceManager.GetString("ChkRemember_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this if you want the system to remember you next time.
        /// </summary>
        public static string ChkRemember_ToolTip {
            get {
                return ResourceManager.GetString("ChkRemember_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can login to the wiki. Don&apos;t you have an account? You can &lt;a href=&quot;/User/Register&quot; title=&quot;Create a new Account&quot;&gt;create one&lt;/a&gt;..
        /// </summary>
        public static string LblDescription_Text {
            get {
                return ResourceManager.GetString("LblDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEmailReset_Text {
            get {
                return ResourceManager.GetString("LblEmailReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are currently logged in. To logout, please click on the Logout button..
        /// </summary>
        public static string LblLogout_Text {
            get {
                return ResourceManager.GetString("LblLogout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LblNewPassword1_Text {
            get {
                return ResourceManager.GetString("LblNewPassword1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (repeat).
        /// </summary>
        public static string LblNewPassword2_Text {
            get {
                return ResourceManager.GetString("LblNewPassword2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string LblOr_Text {
            get {
                return ResourceManager.GetString("LblOr_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LblPassword_Text {
            get {
                return ResourceManager.GetString("LblPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string LblResetPassword_Text {
            get {
                return ResourceManager.GetString("LblResetPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password twice..
        /// </summary>
        public static string LblResetPassword2Info_Text {
            get {
                return ResourceManager.GetString("LblResetPassword2Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you forgot your Password, please insert your Username &lt;b&gt;or&lt;/b&gt; Email address, then click on the Reset Password button.&lt;br /&gt;You will receive an email with a link to reset your password..
        /// </summary>
        public static string LblResetPasswordInformation_Text {
            get {
                return ResourceManager.GetString("LblResetPasswordInformation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LblTitle_Text {
            get {
                return ResourceManager.GetString("LblTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LblUsername_Text {
            get {
                return ResourceManager.GetString("LblUsername_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Page.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required. Length of password must be between 6 and 50..
        /// </summary>
        public static string PasswordSizeMessage {
            get {
                return ResourceManager.GetString("PasswordSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal.
        /// </summary>
        public static string PasswordsNotEqual {
            get {
                return ResourceManager.GetString("PasswordsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string RfvNewPassword1_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvNewPassword1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string RxNewPassword1_ErrorMessage {
            get {
                return ResourceManager.GetString("RxNewPassword1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here your Password.
        /// </summary>
        public static string TxtPassword_ToolTip {
            get {
                return ResourceManager.GetString("TxtPassword_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here your Username.
        /// </summary>
        public static string TxtUsername_ToolTip {
            get {
                return ResourceManager.GetString("TxtUsername_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UsernameIsRequired {
            get {
                return ResourceManager.GetString("UsernameIsRequired", resourceCulture);
            }
        }
    }
}
