//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Common.Profile", typeof(Profile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string BtnConfirm_Text {
            get {
                return ResourceManager.GetString("BtnConfirm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string BtnDeleteAccount_Text {
            get {
                return ResourceManager.GetString("BtnDeleteAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Display Name.
        /// </summary>
        public static string BtnSaveDisplayName_Text {
            get {
                return ResourceManager.GetString("BtnSaveDisplayName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to save your Display Name.
        /// </summary>
        public static string BtnSaveDisplayName_ToolTip {
            get {
                return ResourceManager.GetString("BtnSaveDisplayName_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Email.
        /// </summary>
        public static string BtnSaveEmail_Text {
            get {
                return ResourceManager.GetString("BtnSaveEmail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to save your Email address.
        /// </summary>
        public static string BtnSaveEmail_ToolTip {
            get {
                return ResourceManager.GetString("BtnSaveEmail_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSaveLanguage_Text {
            get {
                return ResourceManager.GetString("BtnSaveLanguage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSaveNotifications_Text {
            get {
                return ResourceManager.GetString("BtnSaveNotifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Password.
        /// </summary>
        public static string BtnSavePassword_Text {
            get {
                return ResourceManager.GetString("BtnSavePassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to save your new Password.
        /// </summary>
        public static string BtnSavePassword_ToolTip {
            get {
                return ResourceManager.GetString("BtnSavePassword_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email addresses are not equal.
        /// </summary>
        public static string CvEmail1_ErrorMessage {
            get {
                return ResourceManager.GetString("CvEmail1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email addresses are not equal.
        /// </summary>
        public static string CvEmail2_ErrorMessage {
            get {
                return ResourceManager.GetString("CvEmail2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string CvOldPassword_ErrorMessage {
            get {
                return ResourceManager.GetString("CvOldPassword_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal.
        /// </summary>
        public static string CvPassword1_ErrorMessage {
            get {
                return ResourceManager.GetString("CvPassword1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal.
        /// </summary>
        public static string CvPassword2_ErrorMessage {
            get {
                return ResourceManager.GetString("CvPassword2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string LblDeleteAccount_Text {
            get {
                return ResourceManager.GetString("LblDeleteAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can delete your account by clicking on the Delete Account button and then confirming with the Confirm button.&lt;br /&gt;&lt;b&gt;Warning&lt;/b&gt;: the operation is irreversible..
        /// </summary>
        public static string LblDeleteAccountInfo_Text {
            get {
                return ResourceManager.GetString("LblDeleteAccountInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your Profile, .
        /// </summary>
        public static string LblDescription_Text {
            get {
                return ResourceManager.GetString("LblDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive an email notification whenever a &lt;b&gt;message&lt;/b&gt; is posted for a page in the following namespaces (only discussions you have access to):.
        /// </summary>
        public static string LblDiscussionMessagesInfo2_Text {
            get {
                return ResourceManager.GetString("LblDiscussionMessagesInfo2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string LblDisplayName_Text {
            get {
                return ResourceManager.GetString("LblDisplayName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Display Name, Email and Password.
        /// </summary>
        public static string LblEditEmailPassword_Text {
            get {
                return ResourceManager.GetString("LblEditEmailPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEmail1_Text {
            get {
                return ResourceManager.GetString("LblEmail1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (repeat).
        /// </summary>
        public static string LblEmail2_Text {
            get {
                return ResourceManager.GetString("LblEmail2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are member of the following groups:.
        /// </summary>
        public static string LblGroups_Text {
            get {
                return ResourceManager.GetString("LblGroups_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can edit your Profile settings, such as Email address and Password. You cannot change your Username..
        /// </summary>
        public static string LblInfo_Text {
            get {
                return ResourceManager.GetString("LblInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language and Time Zone.
        /// </summary>
        public static string LblLanguageTimeZone_Text {
            get {
                return ResourceManager.GetString("LblLanguageTimeZone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current system settings do not allow any change to your personal information..
        /// </summary>
        public static string LblNoChanges_Text {
            get {
                return ResourceManager.GetString("LblNoChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Notification Settings.
        /// </summary>
        public static string LblNotifications_Text {
            get {
                return ResourceManager.GetString("LblNotifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string LblOldPassword_Text {
            get {
                return ResourceManager.GetString("LblOldPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive an email notification whenever a &lt;b&gt;page&lt;/b&gt; in the following namespaces is updated (only pages you have access to):.
        /// </summary>
        public static string LblPageChangesInfo2_Text {
            get {
                return ResourceManager.GetString("LblPageChangesInfo2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LblPassword1_Text {
            get {
                return ResourceManager.GetString("LblPassword1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (repeat).
        /// </summary>
        public static string LblPassword2_Text {
            get {
                return ResourceManager.GetString("LblPassword2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string LblTitle_Text {
            get {
                return ResourceManager.GetString("LblTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Page.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string RfvEmail1_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvEmail1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string RfvEmail2_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvEmail2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is required.
        /// </summary>
        public static string RfvOldPassword_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvOldPassword_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string RfvPassword1_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvPassword1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string RfvPassword2_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvPassword2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Display Name.
        /// </summary>
        public static string RxvDisplayName_ErrorMessage {
            get {
                return ResourceManager.GetString("RxvDisplayName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email address.
        /// </summary>
        public static string RxvEmail1_ErrorMessage {
            get {
                return ResourceManager.GetString("RxvEmail1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string RxvPassword1_ErrorMessage {
            get {
                return ResourceManager.GetString("RxvPassword1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here a display name for your account.
        /// </summary>
        public static string TxtDisplayName_ToolTip {
            get {
                return ResourceManager.GetString("TxtDisplayName_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here your Email address.
        /// </summary>
        public static string TxtEmail1_ToolTip {
            get {
                return ResourceManager.GetString("TxtEmail1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat your Email address.
        /// </summary>
        public static string TxtEmail2_ToolTip {
            get {
                return ResourceManager.GetString("TxtEmail2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here your current Password.
        /// </summary>
        public static string TxtOldPassword_ToolTip {
            get {
                return ResourceManager.GetString("TxtOldPassword_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here your new Password.
        /// </summary>
        public static string TxtPassword1_ToolTip {
            get {
                return ResourceManager.GetString("TxtPassword1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat your new Password.
        /// </summary>
        public static string TxtPassword2_ToolTip {
            get {
                return ResourceManager.GetString("TxtPassword2_ToolTip", resourceCulture);
            }
        }
    }
}
