//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Register {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Register() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Common.Register", typeof(Register).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string BtnRegister_Text {
            get {
                return ResourceManager.GetString("BtnRegister_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to create your Account.
        /// </summary>
        public static string BtnRegister_ToolTip {
            get {
                return ResourceManager.GetString("BtnRegister_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails are not equal.
        /// </summary>
        public static string CvEmail1_ErrorMessage {
            get {
                return ResourceManager.GetString("CvEmail1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails are not equal.
        /// </summary>
        public static string CvEmail2_ErrorMessage {
            get {
                return ResourceManager.GetString("CvEmail2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal.
        /// </summary>
        public static string CvPassword1_ErrorMessage {
            get {
                return ResourceManager.GetString("CvPassword1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal.
        /// </summary>
        public static string CvPassword2_ErrorMessage {
            get {
                return ResourceManager.GetString("CvPassword2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists.
        /// </summary>
        public static string CvUsername_ErrorMessage {
            get {
                return ResourceManager.GetString("CvUsername_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email registered by another user.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Text (case sensitive).
        /// </summary>
        public static string LblCaptcha_Text {
            get {
                return ResourceManager.GetString("LblCaptcha_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string LblDisplayName_Text {
            get {
                return ResourceManager.GetString("LblDisplayName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEmail1_Text {
            get {
                return ResourceManager.GetString("LblEmail1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (repeat).
        /// </summary>
        public static string LblEmail2_Text {
            get {
                return ResourceManager.GetString("LblEmail2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LblPassword1_Text {
            get {
                return ResourceManager.GetString("LblPassword1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (repeat).
        /// </summary>
        public static string LblPassword2_Text {
            get {
                return ResourceManager.GetString("LblPassword2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can create a new Account for this Wiki.&lt;br /&gt;&lt;b&gt;Note&lt;/b&gt;: all the fields are mandatory. The Email address will not be published in any way, but it will be visible to the Administrators..
        /// </summary>
        public static string LblRegisterDescription_Text {
            get {
                return ResourceManager.GetString("LblRegisterDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Account.
        /// </summary>
        public static string LblTitle_Text {
            get {
                return ResourceManager.GetString("LblTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LblUsername_Text {
            get {
                return ResourceManager.GetString("LblUsername_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Page.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string RfvEmail1_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvEmail1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string RfvEmail2_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvEmail2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string RfvPassword1_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvPassword1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string RfvPassword2_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvPassword2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string RfvUsername_ErrorMessage {
            get {
                return ResourceManager.GetString("RfvUsername_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Display Name.
        /// </summary>
        public static string RxvDisplayName_ErrorMessage {
            get {
                return ResourceManager.GetString("RxvDisplayName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string RxvEmail1_ErrorMessage {
            get {
                return ResourceManager.GetString("RxvEmail1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string RxvPassword1_ErrorMessage {
            get {
                return ResourceManager.GetString("RxvPassword1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username.
        /// </summary>
        public static string RxvUserName_ErrorMessage {
            get {
                return ResourceManager.GetString("RxvUserName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here a display name for your account.
        /// </summary>
        public static string TxtDisplayName_ToolTip {
            get {
                return ResourceManager.GetString("TxtDisplayName_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here your Email address.
        /// </summary>
        public static string TxtEmail1_ToolTip {
            get {
                return ResourceManager.GetString("TxtEmail1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat your Email address.
        /// </summary>
        public static string TxtEmail2_ToolTip {
            get {
                return ResourceManager.GetString("TxtEmail2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here your Password.
        /// </summary>
        public static string TxtPassword1_ToolTip {
            get {
                return ResourceManager.GetString("TxtPassword1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat your Password.
        /// </summary>
        public static string TxtPassword2_ToolTip {
            get {
                return ResourceManager.GetString("TxtPassword2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here your Username.
        /// </summary>
        public static string TxtUsername_ToolTip {
            get {
                return ResourceManager.GetString("TxtUsername_ToolTip", resourceCulture);
            }
        }
    }
}
