//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Search {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Search() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Common.Search", typeof(Search).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string BtnGo_Text {
            get {
                return ResourceManager.GetString("BtnGo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in all Namespaces and all Categories.
        /// </summary>
        public static string ChkAllNamespaces_Text {
            get {
                return ResourceManager.GetString("ChkAllNamespaces_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Files and Attachments.
        /// </summary>
        public static string ChkFilesAndAttachments_Text {
            get {
                return ResourceManager.GetString("ChkFilesAndAttachments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized Pages.
        /// </summary>
        public static string ChkUncategorizedPages_Text {
            get {
                return ResourceManager.GetString("ChkUncategorizedPages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Category.
        /// </summary>
        public static string LblCategoryFilter_Text {
            get {
                return ResourceManager.GetString("LblCategoryFilter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can search through the pages of this Namespace, their attachments and the files uploaded to the system.&lt;br /&gt;&lt;b&gt;Note&lt;/b&gt;: the results will only display the items you have permissions to read..
        /// </summary>
        public static string LblInstructions_Text {
            get {
                return ResourceManager.GetString("LblInstructions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string LblSelectAll_Text {
            get {
                return ResourceManager.GetString("LblSelectAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string LblSelectInverse_Text {
            get {
                return ResourceManager.GetString("LblSelectInverse_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LblSelectNone_Text {
            get {
                return ResourceManager.GetString("LblSelectNone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine.
        /// </summary>
        public static string LblTitle_Text {
            get {
                return ResourceManager.GetString("LblTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All words.
        /// </summary>
        public static string RdoAllWords_Text {
            get {
                return ResourceManager.GetString("RdoAllWords_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one word.
        /// </summary>
        public static string RdoAtLeastOneWord_Text {
            get {
                return ResourceManager.GetString("RdoAtLeastOneWord_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact phrase.
        /// </summary>
        public static string RdoExactPhrase_Text {
            get {
                return ResourceManager.GetString("RdoExactPhrase_Text", resourceCulture);
            }
        }
    }
}
